version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DB_USER: root
          DB_NAME: circle_test

      - image: circleci/python:3.8
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
      - image: redis

    steps:
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y libpq-dev

      - run:
          name: Install Git and SSH Client
          command: apt-get install -y ssh git

      - checkout

      - run:
          name: Run Tox
          command: |
            tox